name: Build Lists

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Validation and Build
        uses: Capa-Intelligence/git-access-control/.github/actions/build@v1.0.0
        with:
          lists_dir: lists
          action_ref: v1.0.0
          action_token: ${{ secrets.ACCESS_CONTROL_PAT }}
