name: Build Lists

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Action Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: Capa-Intelligence/git-access-control
          token: ${{ secrets.ACCESS_CONTROL_PAT }}
          ref: v1.0.0


      - name: Run Validation and Build
        uses: ./.github/actions/build
        with:
          lists_dir: lists
          action_ref: v1.0.0
          action_token: ${{ secrets.ACCESS_CONTROL_PAT }}
