name: Create List Bundle Release

on:
  workflow_dispatch: # manual option TODO: Allow?
    inputs:
      release_tag:
        description: "Specify a custom release tag (e.g., v1.0.0). If empty, a timestamped tag will be generated."
        required: false
        type: string

      release_name:
        description: 'Specify a custom release name. If empty, it will be "Release <tag>".'
        required: false
        type: string

      is_draft:
        description: "Create a draft release?"
        required: false
        type: boolean
        default: true

      is_prerelease:
        description: "Create a pre-release?"
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Public Release
        uses: Capa-Intelligence/git-access-control/.github/actions/release@v1.0.0
        with:
          lists_dir: lists
          release_tag: ${{ inputs.release_tag }}
          release_name: ${{ inputs.release_name }}
          is_draft: ${{ inputs.is_draft }}
          is_prerelease: ${{ inputs.is_prerelease }}
          action_ref: v1.0.0
          action_token: ${{ secrets.ACCESS_CONTROL_PAT }}
